# Generated by Django 3.0.2 on 2020-11-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calchistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
